/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.validation;

import br.ufpe.cin.plp.imperativa1.validation.AbstractImperativa1Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Imperativa1Validator extends AbstractImperativa1Validator {
}
