/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Imperativa1StandaloneSetup extends Imperativa1StandaloneSetupGenerated {

	def static void doSetup() {
		new Imperativa1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
