/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class Imperativa1WebModule extends AbstractImperativa1WebModule {
}
