/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class Imperativa1LabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public Imperativa1LabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
