/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.ui;

import br.ufpe.cin.plp.imperativa1.ui.AbstractImperativa1UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Imperativa1UiModule extends AbstractImperativa1UiModule {
  public Imperativa1UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
