/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaracao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDecComposta <em>Dec Composta</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDecVariavel <em>Dec Variavel</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDeclaracao <em>Declaracao</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getDeclaracao()
 * @model
 * @generated
 */
public interface Declaracao extends EObject
{
  /**
   * Returns the value of the '<em><b>Dec Composta</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec Composta</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec Composta</em>' containment reference.
   * @see #setDecComposta(DeclaracaoComposta)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getDeclaracao_DecComposta()
   * @model containment="true"
   * @generated
   */
  DeclaracaoComposta getDecComposta();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDecComposta <em>Dec Composta</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec Composta</em>' containment reference.
   * @see #getDecComposta()
   * @generated
   */
  void setDecComposta(DeclaracaoComposta value);

  /**
   * Returns the value of the '<em><b>Dec Variavel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec Variavel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec Variavel</em>' containment reference.
   * @see #setDecVariavel(DeclaracaoVariavel)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getDeclaracao_DecVariavel()
   * @model containment="true"
   * @generated
   */
  DeclaracaoVariavel getDecVariavel();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDecVariavel <em>Dec Variavel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec Variavel</em>' containment reference.
   * @see #getDecVariavel()
   * @generated
   */
  void setDecVariavel(DeclaracaoVariavel value);

  /**
   * Returns the value of the '<em><b>Declaracao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaracao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaracao</em>' containment reference.
   * @see #setDeclaracao(Declaracao)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getDeclaracao_Declaracao()
   * @model containment="true"
   * @generated
   */
  Declaracao getDeclaracao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao#getDeclaracao <em>Declaracao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaracao</em>' containment reference.
   * @see #getDeclaracao()
   * @generated
   */
  void setDeclaracao(Declaracao value);

} // Declaracao
