/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Binaria</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getSomaExpressao <em>Soma Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getSubExpressao <em>Sub Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getOrExpressao <em>Or Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getAndExpressao <em>And Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getEqualsExpressao <em>Equals Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getConcatExpressao <em>Concat Expressao</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria()
 * @model
 * @generated
 */
public interface ExpBinaria extends EObject
{
  /**
   * Returns the value of the '<em><b>Soma Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Soma Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soma Expressao</em>' containment reference.
   * @see #setSomaExpressao(ExpSoma)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_SomaExpressao()
   * @model containment="true"
   * @generated
   */
  ExpSoma getSomaExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getSomaExpressao <em>Soma Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Soma Expressao</em>' containment reference.
   * @see #getSomaExpressao()
   * @generated
   */
  void setSomaExpressao(ExpSoma value);

  /**
   * Returns the value of the '<em><b>Sub Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Expressao</em>' containment reference.
   * @see #setSubExpressao(ExpSub)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_SubExpressao()
   * @model containment="true"
   * @generated
   */
  ExpSub getSubExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getSubExpressao <em>Sub Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Expressao</em>' containment reference.
   * @see #getSubExpressao()
   * @generated
   */
  void setSubExpressao(ExpSub value);

  /**
   * Returns the value of the '<em><b>Or Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Or Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or Expressao</em>' containment reference.
   * @see #setOrExpressao(ExpOr)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_OrExpressao()
   * @model containment="true"
   * @generated
   */
  ExpOr getOrExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getOrExpressao <em>Or Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or Expressao</em>' containment reference.
   * @see #getOrExpressao()
   * @generated
   */
  void setOrExpressao(ExpOr value);

  /**
   * Returns the value of the '<em><b>And Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>And Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>And Expressao</em>' containment reference.
   * @see #setAndExpressao(ExpAnd)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_AndExpressao()
   * @model containment="true"
   * @generated
   */
  ExpAnd getAndExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getAndExpressao <em>And Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And Expressao</em>' containment reference.
   * @see #getAndExpressao()
   * @generated
   */
  void setAndExpressao(ExpAnd value);

  /**
   * Returns the value of the '<em><b>Equals Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Equals Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equals Expressao</em>' containment reference.
   * @see #setEqualsExpressao(ExpEquals)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_EqualsExpressao()
   * @model containment="true"
   * @generated
   */
  ExpEquals getEqualsExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getEqualsExpressao <em>Equals Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equals Expressao</em>' containment reference.
   * @see #getEqualsExpressao()
   * @generated
   */
  void setEqualsExpressao(ExpEquals value);

  /**
   * Returns the value of the '<em><b>Concat Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concat Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concat Expressao</em>' containment reference.
   * @see #setConcatExpressao(ExpConcat)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpBinaria_ConcatExpressao()
   * @model containment="true"
   * @generated
   */
  ExpConcat getConcatExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria#getConcatExpressao <em>Concat Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concat Expressao</em>' containment reference.
   * @see #getConcatExpressao()
   * @generated
   */
  void setConcatExpressao(ExpConcat value);

} // ExpBinaria
