/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Not</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpNot#getNotExpressao <em>Not Expressao</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpNot()
 * @model
 * @generated
 */
public interface ExpNot extends EObject
{
  /**
   * Returns the value of the '<em><b>Not Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not Expressao</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not Expressao</em>' containment reference.
   * @see #setNotExpressao(Expressao)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpNot_NotExpressao()
   * @model containment="true"
   * @generated
   */
  Expressao getNotExpressao();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.ExpNot#getNotExpressao <em>Not Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not Expressao</em>' containment reference.
   * @see #getNotExpressao()
   * @generated
   */
  void setNotExpressao(Expressao value);

} // ExpNot
