/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpUnaria <em>Exp Unaria</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpPrimaria <em>Exp Primaria</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpBinaria <em>Exp Binaria</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp Unaria</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp Unaria</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Unaria</em>' containment reference.
   * @see #setExpUnaria(ExpUnaria)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpressao_ExpUnaria()
   * @model containment="true"
   * @generated
   */
  ExpUnaria getExpUnaria();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpUnaria <em>Exp Unaria</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Unaria</em>' containment reference.
   * @see #getExpUnaria()
   * @generated
   */
  void setExpUnaria(ExpUnaria value);

  /**
   * Returns the value of the '<em><b>Exp Primaria</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp Primaria</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Primaria</em>' containment reference.
   * @see #setExpPrimaria(ExpPrimaria)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpressao_ExpPrimaria()
   * @model containment="true"
   * @generated
   */
  ExpPrimaria getExpPrimaria();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpPrimaria <em>Exp Primaria</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Primaria</em>' containment reference.
   * @see #getExpPrimaria()
   * @generated
   */
  void setExpPrimaria(ExpPrimaria value);

  /**
   * Returns the value of the '<em><b>Exp Binaria</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp Binaria</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Binaria</em>' containment reference.
   * @see #setExpBinaria(ExpBinaria)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getExpressao_ExpBinaria()
   * @model containment="true"
   * @generated
   */
  ExpBinaria getExpBinaria();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Expressao#getExpBinaria <em>Exp Binaria</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Binaria</em>' containment reference.
   * @see #getExpBinaria()
   * @generated
   */
  void setExpBinaria(ExpBinaria value);

} // Expressao
