/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IO</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.IO#getRead <em>Read</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.IO#getWrite <em>Write</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getIO()
 * @model
 * @generated
 */
public interface IO extends EObject
{
  /**
   * Returns the value of the '<em><b>Read</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Read</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read</em>' containment reference.
   * @see #setRead(Read)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getIO_Read()
   * @model containment="true"
   * @generated
   */
  Read getRead();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.IO#getRead <em>Read</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read</em>' containment reference.
   * @see #getRead()
   * @generated
   */
  void setRead(Read value);

  /**
   * Returns the value of the '<em><b>Write</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write</em>' containment reference.
   * @see #setWrite(Write)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getIO_Write()
   * @model containment="true"
   * @generated
   */
  Write getWrite();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.IO#getWrite <em>Write</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write</em>' containment reference.
   * @see #getWrite()
   * @generated
   */
  void setWrite(Write value);

} // IO
