/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skip</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Skip#getSkip <em>Skip</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getSkip()
 * @model
 * @generated
 */
public interface Skip extends EObject
{
  /**
   * Returns the value of the '<em><b>Skip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Skip</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Skip</em>' attribute.
   * @see #setSkip(String)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getSkip_Skip()
   * @model
   * @generated
   */
  String getSkip();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Skip#getSkip <em>Skip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Skip</em>' attribute.
   * @see #getSkip()
   * @generated
   */
  void setSkip(String value);

} // Skip
