/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Valor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getIntType <em>Int Type</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getStringType <em>String Type</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getBoolType <em>Bool Type</em>}</li>
 * </ul>
 *
 * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getValor()
 * @model
 * @generated
 */
public interface Valor extends EObject
{
  /**
   * Returns the value of the '<em><b>Int Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Type</em>' attribute.
   * @see #setIntType(String)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getValor_IntType()
   * @model
   * @generated
   */
  String getIntType();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getIntType <em>Int Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Type</em>' attribute.
   * @see #getIntType()
   * @generated
   */
  void setIntType(String value);

  /**
   * Returns the value of the '<em><b>String Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Type</em>' attribute.
   * @see #setStringType(String)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getValor_StringType()
   * @model
   * @generated
   */
  String getStringType();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getStringType <em>String Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Type</em>' attribute.
   * @see #getStringType()
   * @generated
   */
  void setStringType(String value);

  /**
   * Returns the value of the '<em><b>Bool Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Type</em>' attribute.
   * @see #setBoolType(String)
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#getValor_BoolType()
   * @model
   * @generated
   */
  String getBoolType();

  /**
   * Sets the value of the '{@link br.ufpe.cin.plp.imperativa1.imperativa1.Valor#getBoolType <em>Bool Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Type</em>' attribute.
   * @see #getBoolType()
   * @generated
   */
  void setBoolType(String value);

} // Valor
