/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class Imperativa1QuickfixProvider extends DefaultQuickfixProvider {
}
