/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.ui;

import br.ufpe.cin.plp.imperativa1.ui.internal.Imperativa1Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Imperativa1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Imperativa1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Imperativa1Activator.getInstance().getInjector(Imperativa1Activator.BR_UFPE_CIN_PLP_IMPERATIVA1_IMPERATIVA1);
	}
	
}
