/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractImperativa1Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package.eINSTANCE);
		return result;
	}
	
}
