/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class Imperativa1ScopeProvider extends AbstractImperativa1ScopeProvider {

}
