/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.web;

import br.ufpe.cin.plp.imperativa1.ide.contentassist.antlr.Imperativa1Parser;
import br.ufpe.cin.plp.imperativa1.ide.contentassist.antlr.internal.InternalImperativa1Lexer;
import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link Imperativa1WebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractImperativa1WebModule extends DefaultWebModule {

	public AbstractImperativa1WebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalImperativa1Lexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return Imperativa1Parser.class;
	}
	
}
