/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1;

import br.ufpe.cin.plp.imperativa1.Imperativa1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Imperativa1StandaloneSetup extends Imperativa1StandaloneSetupGenerated {
  public static void doSetup() {
    Imperativa1StandaloneSetup _imperativa1StandaloneSetup = new Imperativa1StandaloneSetup();
    _imperativa1StandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
