/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1;

import br.ufpe.cin.plp.imperativa1.AbstractImperativa1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Imperativa1RuntimeModule extends AbstractImperativa1RuntimeModule {
}
