/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractImperativa1ScopeProvider extends DelegatingScopeProvider {
}
