/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.ui.contentassist;

import br.ufpe.cin.plp.imperativa1.ui.contentassist.AbstractImperativa1ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Imperativa1ProposalProvider extends AbstractImperativa1ProposalProvider {
}
