/*
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Imperativa1AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/ufpe/cin/plp/imperativa1/parser/antlr/internal/InternalImperativa1.tokens");
	}
}
