/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1.impl;

import br.ufpe.cin.plp.imperativa1.imperativa1.ExpLenght;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpMenos;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpNot;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpUnaria;
import br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Unaria</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.impl.ExpUnariaImpl#getMenosExpressao <em>Menos Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.impl.ExpUnariaImpl#getNotExpressao <em>Not Expressao</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.impl.ExpUnariaImpl#getLengthExpressao <em>Length Expressao</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExpUnariaImpl extends MinimalEObjectImpl.Container implements ExpUnaria
{
  /**
   * The cached value of the '{@link #getMenosExpressao() <em>Menos Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMenosExpressao()
   * @generated
   * @ordered
   */
  protected ExpMenos menosExpressao;

  /**
   * The cached value of the '{@link #getNotExpressao() <em>Not Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotExpressao()
   * @generated
   * @ordered
   */
  protected ExpNot notExpressao;

  /**
   * The cached value of the '{@link #getLengthExpressao() <em>Length Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLengthExpressao()
   * @generated
   * @ordered
   */
  protected ExpLenght lengthExpressao;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpUnariaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Imperativa1Package.Literals.EXP_UNARIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExpMenos getMenosExpressao()
  {
    return menosExpressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMenosExpressao(ExpMenos newMenosExpressao, NotificationChain msgs)
  {
    ExpMenos oldMenosExpressao = menosExpressao;
    menosExpressao = newMenosExpressao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO, oldMenosExpressao, newMenosExpressao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMenosExpressao(ExpMenos newMenosExpressao)
  {
    if (newMenosExpressao != menosExpressao)
    {
      NotificationChain msgs = null;
      if (menosExpressao != null)
        msgs = ((InternalEObject)menosExpressao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO, null, msgs);
      if (newMenosExpressao != null)
        msgs = ((InternalEObject)newMenosExpressao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO, null, msgs);
      msgs = basicSetMenosExpressao(newMenosExpressao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO, newMenosExpressao, newMenosExpressao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExpNot getNotExpressao()
  {
    return notExpressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNotExpressao(ExpNot newNotExpressao, NotificationChain msgs)
  {
    ExpNot oldNotExpressao = notExpressao;
    notExpressao = newNotExpressao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO, oldNotExpressao, newNotExpressao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNotExpressao(ExpNot newNotExpressao)
  {
    if (newNotExpressao != notExpressao)
    {
      NotificationChain msgs = null;
      if (notExpressao != null)
        msgs = ((InternalEObject)notExpressao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO, null, msgs);
      if (newNotExpressao != null)
        msgs = ((InternalEObject)newNotExpressao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO, null, msgs);
      msgs = basicSetNotExpressao(newNotExpressao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO, newNotExpressao, newNotExpressao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExpLenght getLengthExpressao()
  {
    return lengthExpressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLengthExpressao(ExpLenght newLengthExpressao, NotificationChain msgs)
  {
    ExpLenght oldLengthExpressao = lengthExpressao;
    lengthExpressao = newLengthExpressao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO, oldLengthExpressao, newLengthExpressao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLengthExpressao(ExpLenght newLengthExpressao)
  {
    if (newLengthExpressao != lengthExpressao)
    {
      NotificationChain msgs = null;
      if (lengthExpressao != null)
        msgs = ((InternalEObject)lengthExpressao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO, null, msgs);
      if (newLengthExpressao != null)
        msgs = ((InternalEObject)newLengthExpressao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO, null, msgs);
      msgs = basicSetLengthExpressao(newLengthExpressao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO, newLengthExpressao, newLengthExpressao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO:
        return basicSetMenosExpressao(null, msgs);
      case Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO:
        return basicSetNotExpressao(null, msgs);
      case Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO:
        return basicSetLengthExpressao(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO:
        return getMenosExpressao();
      case Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO:
        return getNotExpressao();
      case Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO:
        return getLengthExpressao();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO:
        setMenosExpressao((ExpMenos)newValue);
        return;
      case Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO:
        setNotExpressao((ExpNot)newValue);
        return;
      case Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO:
        setLengthExpressao((ExpLenght)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO:
        setMenosExpressao((ExpMenos)null);
        return;
      case Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO:
        setNotExpressao((ExpNot)null);
        return;
      case Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO:
        setLengthExpressao((ExpLenght)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Imperativa1Package.EXP_UNARIA__MENOS_EXPRESSAO:
        return menosExpressao != null;
      case Imperativa1Package.EXP_UNARIA__NOT_EXPRESSAO:
        return notExpressao != null;
      case Imperativa1Package.EXP_UNARIA__LENGTH_EXPRESSAO:
        return lengthExpressao != null;
    }
    return super.eIsSet(featureID);
  }

} //ExpUnariaImpl
