/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1.impl;

import br.ufpe.cin.plp.imperativa1.imperativa1.Atribuicao;
import br.ufpe.cin.plp.imperativa1.imperativa1.Comando;
import br.ufpe.cin.plp.imperativa1.imperativa1.ComandoDeclaracao;
import br.ufpe.cin.plp.imperativa1.imperativa1.ComandoSimples;
import br.ufpe.cin.plp.imperativa1.imperativa1.Declaracao;
import br.ufpe.cin.plp.imperativa1.imperativa1.DeclaracaoComposta;
import br.ufpe.cin.plp.imperativa1.imperativa1.DeclaracaoVariavel;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpAnd;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpBinaria;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpConcat;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpEquals;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpLenght;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpMenos;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpNot;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpOr;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpPrimaria;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpSoma;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpSub;
import br.ufpe.cin.plp.imperativa1.imperativa1.ExpUnaria;
import br.ufpe.cin.plp.imperativa1.imperativa1.Expressao;
import br.ufpe.cin.plp.imperativa1.imperativa1.IfThenElse;
import br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Factory;
import br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package;
import br.ufpe.cin.plp.imperativa1.imperativa1.Model;
import br.ufpe.cin.plp.imperativa1.imperativa1.Read;
import br.ufpe.cin.plp.imperativa1.imperativa1.SequenciaComando;
import br.ufpe.cin.plp.imperativa1.imperativa1.Skip;
import br.ufpe.cin.plp.imperativa1.imperativa1.Valor;
import br.ufpe.cin.plp.imperativa1.imperativa1.While;
import br.ufpe.cin.plp.imperativa1.imperativa1.Write;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Imperativa1PackageImpl extends EPackageImpl implements Imperativa1Package
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sequenciaComandoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass readEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass writeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ifThenElseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whileEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass skipEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atribuicaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass valorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expMenosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expNotEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expLenghtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expPrimariaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expUnariaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expBinariaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expSomaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expSubEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expAndEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expOrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expEqualsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expConcatEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoSimplesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoDeclaracaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoCompostaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoVariavelEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package#eNS_URI
   * @see #init()
   * @generated
   */
  private Imperativa1PackageImpl()
  {
    super(eNS_URI, Imperativa1Factory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link Imperativa1Package#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static Imperativa1Package init()
  {
    if (isInited) return (Imperativa1Package)EPackage.Registry.INSTANCE.getEPackage(Imperativa1Package.eNS_URI);

    // Obtain or create and register package
    Imperativa1PackageImpl theImperativa1Package = (Imperativa1PackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof Imperativa1PackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new Imperativa1PackageImpl());

    isInited = true;

    // Create package meta-data objects
    theImperativa1Package.createPackageContents();

    // Initialize created meta-data
    theImperativa1Package.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theImperativa1Package.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(Imperativa1Package.eNS_URI, theImperativa1Package);
    return theImperativa1Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Comandos()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getComando()
  {
    return comandoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComando_SequenciaComando()
  {
    return (EReference)comandoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComando_ComandoSimples()
  {
    return (EReference)comandoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSequenciaComando()
  {
    return sequenciaComandoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSequenciaComando_ComandoSimples()
  {
    return (EReference)sequenciaComandoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSequenciaComando_Comando()
  {
    return (EReference)sequenciaComandoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIO()
  {
    return ioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getIO_Read()
  {
    return (EReference)ioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getIO_Write()
  {
    return (EReference)ioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRead()
  {
    return readEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRead_Pid()
  {
    return (EAttribute)readEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWrite()
  {
    return writeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWrite_Expressao()
  {
    return (EReference)writeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIfThenElse()
  {
    return ifThenElseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getIfThenElse_Expressao()
  {
    return (EReference)ifThenElseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getIfThenElse_Comando()
  {
    return (EReference)ifThenElseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhile()
  {
    return whileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhile_Expressao()
  {
    return (EReference)whileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhile_Comando()
  {
    return (EReference)whileEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSkip()
  {
    return skipEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSkip_Skip()
  {
    return (EAttribute)skipEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtribuicao()
  {
    return atribuicaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAtribuicao_Pid()
  {
    return (EAttribute)atribuicaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAtribuicao_Expressao()
  {
    return (EReference)atribuicaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getValor()
  {
    return valorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getValor_IntType()
  {
    return (EAttribute)valorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getValor_StringType()
  {
    return (EAttribute)valorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getValor_BoolType()
  {
    return (EAttribute)valorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpMenos()
  {
    return expMenosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpMenos_MenosExpressao()
  {
    return (EReference)expMenosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpNot()
  {
    return expNotEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpNot_NotExpressao()
  {
    return (EReference)expNotEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpLenght()
  {
    return expLenghtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpLenght_LengthExpressao()
  {
    return (EReference)expLenghtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpPrimaria()
  {
    return expPrimariaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getExpPrimaria_Pid()
  {
    return (EAttribute)expPrimariaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpPrimaria_Valor()
  {
    return (EReference)expPrimariaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpPrimaria_Expressao()
  {
    return (EReference)expPrimariaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpUnaria()
  {
    return expUnariaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpUnaria_MenosExpressao()
  {
    return (EReference)expUnariaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpUnaria_NotExpressao()
  {
    return (EReference)expUnariaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpUnaria_LengthExpressao()
  {
    return (EReference)expUnariaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpBinaria()
  {
    return expBinariaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_SomaExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_SubExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_OrExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_AndExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_EqualsExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpBinaria_ConcatExpressao()
  {
    return (EReference)expBinariaEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpSoma()
  {
    return expSomaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpSoma_Valor()
  {
    return (EReference)expSomaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpSoma_Expressao()
  {
    return (EReference)expSomaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpSub()
  {
    return expSubEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpSub_Valor()
  {
    return (EReference)expSubEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpSub_Expressao()
  {
    return (EReference)expSubEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpAnd()
  {
    return expAndEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpAnd_Valor()
  {
    return (EReference)expAndEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpAnd_Expressao()
  {
    return (EReference)expAndEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpOr()
  {
    return expOrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpOr_Valor()
  {
    return (EReference)expOrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpOr_Expressao()
  {
    return (EReference)expOrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpEquals()
  {
    return expEqualsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpEquals_Valor()
  {
    return (EReference)expEqualsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpEquals_Expressao()
  {
    return (EReference)expEqualsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpConcat()
  {
    return expConcatEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpConcat_Valor()
  {
    return (EReference)expConcatEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpConcat_Expressao()
  {
    return (EReference)expConcatEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpressao()
  {
    return expressaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpressao_ExpUnaria()
  {
    return (EReference)expressaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpressao_ExpPrimaria()
  {
    return (EReference)expressaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpressao_ExpBinaria()
  {
    return (EReference)expressaoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getComandoSimples()
  {
    return comandoSimplesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_Skip()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_Atribuicao()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_ComandoDeclaracao()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_While()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_IfThenElse()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_Io()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoSimples_Comando()
  {
    return (EReference)comandoSimplesEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getComandoDeclaracao()
  {
    return comandoDeclaracaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoDeclaracao_Declaracao()
  {
    return (EReference)comandoDeclaracaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComandoDeclaracao_Comando()
  {
    return (EReference)comandoDeclaracaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeclaracao()
  {
    return declaracaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracao_DecComposta()
  {
    return (EReference)declaracaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracao_DecVariavel()
  {
    return (EReference)declaracaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracao_Declaracao()
  {
    return (EReference)declaracaoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeclaracaoComposta()
  {
    return declaracaoCompostaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracaoComposta_DecVariavel()
  {
    return (EReference)declaracaoCompostaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracaoComposta_Declaracao()
  {
    return (EReference)declaracaoCompostaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeclaracaoVariavel()
  {
    return declaracaoVariavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDeclaracaoVariavel_Pid()
  {
    return (EAttribute)declaracaoVariavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDeclaracaoVariavel_Expressao()
  {
    return (EReference)declaracaoVariavelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Imperativa1Factory getImperativa1Factory()
  {
    return (Imperativa1Factory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__COMANDOS);

    comandoEClass = createEClass(COMANDO);
    createEReference(comandoEClass, COMANDO__SEQUENCIA_COMANDO);
    createEReference(comandoEClass, COMANDO__COMANDO_SIMPLES);

    sequenciaComandoEClass = createEClass(SEQUENCIA_COMANDO);
    createEReference(sequenciaComandoEClass, SEQUENCIA_COMANDO__COMANDO_SIMPLES);
    createEReference(sequenciaComandoEClass, SEQUENCIA_COMANDO__COMANDO);

    ioEClass = createEClass(IO);
    createEReference(ioEClass, IO__READ);
    createEReference(ioEClass, IO__WRITE);

    readEClass = createEClass(READ);
    createEAttribute(readEClass, READ__PID);

    writeEClass = createEClass(WRITE);
    createEReference(writeEClass, WRITE__EXPRESSAO);

    ifThenElseEClass = createEClass(IF_THEN_ELSE);
    createEReference(ifThenElseEClass, IF_THEN_ELSE__EXPRESSAO);
    createEReference(ifThenElseEClass, IF_THEN_ELSE__COMANDO);

    whileEClass = createEClass(WHILE);
    createEReference(whileEClass, WHILE__EXPRESSAO);
    createEReference(whileEClass, WHILE__COMANDO);

    skipEClass = createEClass(SKIP);
    createEAttribute(skipEClass, SKIP__SKIP);

    atribuicaoEClass = createEClass(ATRIBUICAO);
    createEAttribute(atribuicaoEClass, ATRIBUICAO__PID);
    createEReference(atribuicaoEClass, ATRIBUICAO__EXPRESSAO);

    valorEClass = createEClass(VALOR);
    createEAttribute(valorEClass, VALOR__INT_TYPE);
    createEAttribute(valorEClass, VALOR__STRING_TYPE);
    createEAttribute(valorEClass, VALOR__BOOL_TYPE);

    expMenosEClass = createEClass(EXP_MENOS);
    createEReference(expMenosEClass, EXP_MENOS__MENOS_EXPRESSAO);

    expNotEClass = createEClass(EXP_NOT);
    createEReference(expNotEClass, EXP_NOT__NOT_EXPRESSAO);

    expLenghtEClass = createEClass(EXP_LENGHT);
    createEReference(expLenghtEClass, EXP_LENGHT__LENGTH_EXPRESSAO);

    expPrimariaEClass = createEClass(EXP_PRIMARIA);
    createEAttribute(expPrimariaEClass, EXP_PRIMARIA__PID);
    createEReference(expPrimariaEClass, EXP_PRIMARIA__VALOR);
    createEReference(expPrimariaEClass, EXP_PRIMARIA__EXPRESSAO);

    expUnariaEClass = createEClass(EXP_UNARIA);
    createEReference(expUnariaEClass, EXP_UNARIA__MENOS_EXPRESSAO);
    createEReference(expUnariaEClass, EXP_UNARIA__NOT_EXPRESSAO);
    createEReference(expUnariaEClass, EXP_UNARIA__LENGTH_EXPRESSAO);

    expBinariaEClass = createEClass(EXP_BINARIA);
    createEReference(expBinariaEClass, EXP_BINARIA__SOMA_EXPRESSAO);
    createEReference(expBinariaEClass, EXP_BINARIA__SUB_EXPRESSAO);
    createEReference(expBinariaEClass, EXP_BINARIA__OR_EXPRESSAO);
    createEReference(expBinariaEClass, EXP_BINARIA__AND_EXPRESSAO);
    createEReference(expBinariaEClass, EXP_BINARIA__EQUALS_EXPRESSAO);
    createEReference(expBinariaEClass, EXP_BINARIA__CONCAT_EXPRESSAO);

    expSomaEClass = createEClass(EXP_SOMA);
    createEReference(expSomaEClass, EXP_SOMA__VALOR);
    createEReference(expSomaEClass, EXP_SOMA__EXPRESSAO);

    expSubEClass = createEClass(EXP_SUB);
    createEReference(expSubEClass, EXP_SUB__VALOR);
    createEReference(expSubEClass, EXP_SUB__EXPRESSAO);

    expAndEClass = createEClass(EXP_AND);
    createEReference(expAndEClass, EXP_AND__VALOR);
    createEReference(expAndEClass, EXP_AND__EXPRESSAO);

    expOrEClass = createEClass(EXP_OR);
    createEReference(expOrEClass, EXP_OR__VALOR);
    createEReference(expOrEClass, EXP_OR__EXPRESSAO);

    expEqualsEClass = createEClass(EXP_EQUALS);
    createEReference(expEqualsEClass, EXP_EQUALS__VALOR);
    createEReference(expEqualsEClass, EXP_EQUALS__EXPRESSAO);

    expConcatEClass = createEClass(EXP_CONCAT);
    createEReference(expConcatEClass, EXP_CONCAT__VALOR);
    createEReference(expConcatEClass, EXP_CONCAT__EXPRESSAO);

    expressaoEClass = createEClass(EXPRESSAO);
    createEReference(expressaoEClass, EXPRESSAO__EXP_UNARIA);
    createEReference(expressaoEClass, EXPRESSAO__EXP_PRIMARIA);
    createEReference(expressaoEClass, EXPRESSAO__EXP_BINARIA);

    comandoSimplesEClass = createEClass(COMANDO_SIMPLES);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__SKIP);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__ATRIBUICAO);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__COMANDO_DECLARACAO);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__WHILE);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__IF_THEN_ELSE);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__IO);
    createEReference(comandoSimplesEClass, COMANDO_SIMPLES__COMANDO);

    comandoDeclaracaoEClass = createEClass(COMANDO_DECLARACAO);
    createEReference(comandoDeclaracaoEClass, COMANDO_DECLARACAO__DECLARACAO);
    createEReference(comandoDeclaracaoEClass, COMANDO_DECLARACAO__COMANDO);

    declaracaoEClass = createEClass(DECLARACAO);
    createEReference(declaracaoEClass, DECLARACAO__DEC_COMPOSTA);
    createEReference(declaracaoEClass, DECLARACAO__DEC_VARIAVEL);
    createEReference(declaracaoEClass, DECLARACAO__DECLARACAO);

    declaracaoCompostaEClass = createEClass(DECLARACAO_COMPOSTA);
    createEReference(declaracaoCompostaEClass, DECLARACAO_COMPOSTA__DEC_VARIAVEL);
    createEReference(declaracaoCompostaEClass, DECLARACAO_COMPOSTA__DECLARACAO);

    declaracaoVariavelEClass = createEClass(DECLARACAO_VARIAVEL);
    createEAttribute(declaracaoVariavelEClass, DECLARACAO_VARIAVEL__PID);
    createEReference(declaracaoVariavelEClass, DECLARACAO_VARIAVEL__EXPRESSAO);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Comandos(), this.getComando(), null, "comandos", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoEClass, Comando.class, "Comando", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComando_SequenciaComando(), this.getSequenciaComando(), null, "sequenciaComando", null, 0, 1, Comando.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComando_ComandoSimples(), this.getComandoSimples(), null, "comandoSimples", null, 0, 1, Comando.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sequenciaComandoEClass, SequenciaComando.class, "SequenciaComando", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSequenciaComando_ComandoSimples(), this.getComandoSimples(), null, "comandoSimples", null, 0, 1, SequenciaComando.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSequenciaComando_Comando(), this.getComando(), null, "comando", null, 0, 1, SequenciaComando.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ioEClass, br.ufpe.cin.plp.imperativa1.imperativa1.IO.class, "IO", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIO_Read(), this.getRead(), null, "read", null, 0, 1, br.ufpe.cin.plp.imperativa1.imperativa1.IO.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIO_Write(), this.getWrite(), null, "write", null, 0, 1, br.ufpe.cin.plp.imperativa1.imperativa1.IO.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(readEClass, Read.class, "Read", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRead_Pid(), ecorePackage.getEString(), "pid", null, 0, 1, Read.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(writeEClass, Write.class, "Write", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWrite_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, Write.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ifThenElseEClass, IfThenElse.class, "IfThenElse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIfThenElse_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, IfThenElse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIfThenElse_Comando(), this.getComando(), null, "comando", null, 0, 1, IfThenElse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(whileEClass, While.class, "While", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWhile_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, While.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWhile_Comando(), this.getComando(), null, "comando", null, 0, 1, While.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(skipEClass, Skip.class, "Skip", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSkip_Skip(), ecorePackage.getEString(), "skip", null, 0, 1, Skip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atribuicaoEClass, Atribuicao.class, "Atribuicao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAtribuicao_Pid(), ecorePackage.getEString(), "pid", null, 0, 1, Atribuicao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAtribuicao_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, Atribuicao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(valorEClass, Valor.class, "Valor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getValor_IntType(), ecorePackage.getEString(), "intType", null, 0, 1, Valor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getValor_StringType(), ecorePackage.getEString(), "stringType", null, 0, 1, Valor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getValor_BoolType(), ecorePackage.getEString(), "boolType", null, 0, 1, Valor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expMenosEClass, ExpMenos.class, "ExpMenos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpMenos_MenosExpressao(), this.getExpressao(), null, "menosExpressao", null, 0, 1, ExpMenos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expNotEClass, ExpNot.class, "ExpNot", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpNot_NotExpressao(), this.getExpressao(), null, "notExpressao", null, 0, 1, ExpNot.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expLenghtEClass, ExpLenght.class, "ExpLenght", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpLenght_LengthExpressao(), this.getExpressao(), null, "lengthExpressao", null, 0, 1, ExpLenght.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expPrimariaEClass, ExpPrimaria.class, "ExpPrimaria", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExpPrimaria_Pid(), ecorePackage.getEString(), "pid", null, 0, 1, ExpPrimaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpPrimaria_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpPrimaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpPrimaria_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpPrimaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expUnariaEClass, ExpUnaria.class, "ExpUnaria", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpUnaria_MenosExpressao(), this.getExpMenos(), null, "menosExpressao", null, 0, 1, ExpUnaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpUnaria_NotExpressao(), this.getExpNot(), null, "notExpressao", null, 0, 1, ExpUnaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpUnaria_LengthExpressao(), this.getExpLenght(), null, "lengthExpressao", null, 0, 1, ExpUnaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expBinariaEClass, ExpBinaria.class, "ExpBinaria", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpBinaria_SomaExpressao(), this.getExpSoma(), null, "somaExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpBinaria_SubExpressao(), this.getExpSub(), null, "subExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpBinaria_OrExpressao(), this.getExpOr(), null, "orExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpBinaria_AndExpressao(), this.getExpAnd(), null, "andExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpBinaria_EqualsExpressao(), this.getExpEquals(), null, "equalsExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpBinaria_ConcatExpressao(), this.getExpConcat(), null, "concatExpressao", null, 0, 1, ExpBinaria.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expSomaEClass, ExpSoma.class, "ExpSoma", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpSoma_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpSoma.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpSoma_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpSoma.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expSubEClass, ExpSub.class, "ExpSub", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpSub_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpSub.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpSub_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpSub.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expAndEClass, ExpAnd.class, "ExpAnd", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpAnd_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpAnd.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpAnd_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpAnd.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expOrEClass, ExpOr.class, "ExpOr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpOr_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpOr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpOr_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpOr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expEqualsEClass, ExpEquals.class, "ExpEquals", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpEquals_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpEquals.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpEquals_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpEquals.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expConcatEClass, ExpConcat.class, "ExpConcat", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpConcat_Valor(), this.getValor(), null, "valor", null, 0, 1, ExpConcat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpConcat_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, ExpConcat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoEClass, Expressao.class, "Expressao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpressao_ExpUnaria(), this.getExpUnaria(), null, "expUnaria", null, 0, 1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpressao_ExpPrimaria(), this.getExpPrimaria(), null, "expPrimaria", null, 0, 1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpressao_ExpBinaria(), this.getExpBinaria(), null, "expBinaria", null, 0, 1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoSimplesEClass, ComandoSimples.class, "ComandoSimples", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoSimples_Skip(), this.getSkip(), null, "skip", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_Atribuicao(), this.getAtribuicao(), null, "atribuicao", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_ComandoDeclaracao(), this.getComandoDeclaracao(), null, "comandoDeclaracao", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_While(), this.getWhile(), null, "while", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_IfThenElse(), this.getIfThenElse(), null, "ifThenElse", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_Io(), this.getIO(), null, "io", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSimples_Comando(), this.getComando(), null, "comando", null, 0, 1, ComandoSimples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoDeclaracaoEClass, ComandoDeclaracao.class, "ComandoDeclaracao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoDeclaracao_Declaracao(), this.getDeclaracao(), null, "declaracao", null, 0, 1, ComandoDeclaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoDeclaracao_Comando(), this.getComando(), null, "comando", null, 0, 1, ComandoDeclaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoEClass, Declaracao.class, "Declaracao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclaracao_DecComposta(), this.getDeclaracaoComposta(), null, "decComposta", null, 0, 1, Declaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracao_DecVariavel(), this.getDeclaracaoVariavel(), null, "decVariavel", null, 0, 1, Declaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracao_Declaracao(), this.getDeclaracao(), null, "declaracao", null, 0, 1, Declaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoCompostaEClass, DeclaracaoComposta.class, "DeclaracaoComposta", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclaracaoComposta_DecVariavel(), this.getDeclaracaoVariavel(), null, "decVariavel", null, 0, 1, DeclaracaoComposta.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracaoComposta_Declaracao(), this.getDeclaracao(), null, "declaracao", null, 0, 1, DeclaracaoComposta.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoVariavelEClass, DeclaracaoVariavel.class, "DeclaracaoVariavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclaracaoVariavel_Pid(), ecorePackage.getEString(), "pid", null, 0, 1, DeclaracaoVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracaoVariavel_Expressao(), this.getExpressao(), null, "expressao", null, 0, 1, DeclaracaoVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //Imperativa1PackageImpl
