/**
 * generated by Xtext 2.9.2
 */
package br.ufpe.cin.plp.imperativa1.imperativa1.impl;

import br.ufpe.cin.plp.imperativa1.imperativa1.IO;
import br.ufpe.cin.plp.imperativa1.imperativa1.Imperativa1Package;
import br.ufpe.cin.plp.imperativa1.imperativa1.Read;
import br.ufpe.cin.plp.imperativa1.imperativa1.Write;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>IO</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.impl.IOImpl#getRead <em>Read</em>}</li>
 *   <li>{@link br.ufpe.cin.plp.imperativa1.imperativa1.impl.IOImpl#getWrite <em>Write</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IOImpl extends MinimalEObjectImpl.Container implements IO
{
  /**
   * The cached value of the '{@link #getRead() <em>Read</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRead()
   * @generated
   * @ordered
   */
  protected Read read;

  /**
   * The cached value of the '{@link #getWrite() <em>Write</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWrite()
   * @generated
   * @ordered
   */
  protected Write write;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IOImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Imperativa1Package.Literals.IO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Read getRead()
  {
    return read;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRead(Read newRead, NotificationChain msgs)
  {
    Read oldRead = read;
    read = newRead;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Imperativa1Package.IO__READ, oldRead, newRead);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRead(Read newRead)
  {
    if (newRead != read)
    {
      NotificationChain msgs = null;
      if (read != null)
        msgs = ((InternalEObject)read).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.IO__READ, null, msgs);
      if (newRead != null)
        msgs = ((InternalEObject)newRead).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.IO__READ, null, msgs);
      msgs = basicSetRead(newRead, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Imperativa1Package.IO__READ, newRead, newRead));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Write getWrite()
  {
    return write;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWrite(Write newWrite, NotificationChain msgs)
  {
    Write oldWrite = write;
    write = newWrite;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Imperativa1Package.IO__WRITE, oldWrite, newWrite);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWrite(Write newWrite)
  {
    if (newWrite != write)
    {
      NotificationChain msgs = null;
      if (write != null)
        msgs = ((InternalEObject)write).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.IO__WRITE, null, msgs);
      if (newWrite != null)
        msgs = ((InternalEObject)newWrite).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Imperativa1Package.IO__WRITE, null, msgs);
      msgs = basicSetWrite(newWrite, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Imperativa1Package.IO__WRITE, newWrite, newWrite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Imperativa1Package.IO__READ:
        return basicSetRead(null, msgs);
      case Imperativa1Package.IO__WRITE:
        return basicSetWrite(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Imperativa1Package.IO__READ:
        return getRead();
      case Imperativa1Package.IO__WRITE:
        return getWrite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Imperativa1Package.IO__READ:
        setRead((Read)newValue);
        return;
      case Imperativa1Package.IO__WRITE:
        setWrite((Write)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Imperativa1Package.IO__READ:
        setRead((Read)null);
        return;
      case Imperativa1Package.IO__WRITE:
        setWrite((Write)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Imperativa1Package.IO__READ:
        return read != null;
      case Imperativa1Package.IO__WRITE:
        return write != null;
    }
    return super.eIsSet(featureID);
  }

} //IOImpl
